### ISSUE TITLE
syncy removes dest directory with ignored files

### ISSUE THREAD

**Issue by akaegi** [mrmlnc/syncy#26]
`syncy('fixtures/**', '.tmp/ignore-1', { updateAndDelete: true, ignoreInDest: '**/*.js' })`
deletes a file .tmp/ignore-1/main/test-0.js what is not expected (at least by me ;-).

I will add a test spec for you asap.

**Comment by akaegi** [comment]
Cannot push my test spec to a new branch...
Here is the spec anyway
```typescript
it('ignore-1: Don\'t remove directory with ignored files', () => {		
    return createFiles('.tmp/ignore-1/main', 1, 'js')
        .then(() => syncy('fixtures/**', '.tmp/ignore-1', { updateAndDelete: true, ignoreInDest: '**/*.js' }))
        .then(() => readdir('.tmp/ignore-1/main'))
        .then((result) => {
            assert.equal(result.length, 1);
        });
});
```

**Comment by akaegi** [comment]
Just discovered another weirdness. In response to the above bug I disabled option updateAndDelete. 

The documentation says "// Remove all files from dest that are not found in src. Default: true".

However it seems that without this option, files changes in src are not updated in dest anymore, is this correct? Then the documentation would be confusing...

**Comment by mrmlnc** [comment]
Hello, @akaegi,

Thanks for your report. I'll look at this Issue today.

**Comment by mrmlnc** [comment]
Confirm. Syncy regardless of the settings removes directories.

**Comment by mrmlnc** [comment]
Fixed in 2.2.1.

**Comment by akaegi** [comment]
Thanks for your quick fix, unfortunately it does not work for me :-(
syncy now removes all .js files in dest/app with the following config:

```javascript
const syncyOptions = {
    base: 'app',
    verbose: true,
    updateAndDelete: true,
    ignoreInDest: ['**/*.js', '**/*.js.map']
};

syncy(['app/**/*.html', 'app/**/*.css'], 'dest/app', syncyOptions);
```

**Comment by mrmlnc** [comment]
I spent several manual tests, and now your problem should be solved. Please, try to use `2.2.2` and sorry for this situation.

Well, as I suspected, need to migrate from `node-glob` to custom solution. Now we do a lot of unnecessary actions.

**Comment by akaegi** [comment]
Thank you. Tested it and it now works fine. Thanks for your effort.
