### ISSUE TITLE
ignoreInDest error

### ISSUE THREAD

**Issue by Exuraz** [mrmlnc/syncy#4]
Hi,

While setting up my Gulp with Syncy, I came across the following error:
_[TypeError: glob pattern string required]_

This is my gulp.task, with Syncy:

```
> gulp.task('sync', function() {
    syncy(path.sync_src, path.sync_dest,
        {
            base: 'src',
            updateAndDelete: true,
            ignoreInDest: [path.sync_dest_ignore]
        })
        .on('error', console.error)
        .end();
});

```
where `path.sync_dest_ignore` references the following:

> ` var path = {
 sync_dest_ignore : [
        'src/css/**',
        'src/js/**'
    ]`
};

When I remove `ignoreInDest`, the error doesn't occur.

Versions:
Gulp: ^3.9.1
Syncy: ^1.0.2

**Comment by mrmlnc** [comment]
Hello,

In your example, you pass an array in the array:

```js
ignoreInDest: [path.sync_dest_ignore]

...
sync_dest_ignore : [ 'src/css/**', 'src/js/**' ]
```

In the end, it turns out:

```js
ignoreInDest: [[ 'src/css/**', 'src/js/**' ]]
```

**Comment by Exuraz** [comment]
Oh, sorry. I'm not that good with JavaScript yet haha, I saw this somewhere else so I thought it was the correct syntax. Thanks!

**Comment by mrmlnc** [comment]
No problem, glad it is resolved :)
