### ISSUE TITLE
Incorrect documentation of the updateAndDelete option

### ISSUE THREAD

**Issue by sbx320** [mrmlnc/syncy#9]
Hi,
I just stumbled over the following documentation in the Readme.md

> // Remove all files from dest that are not found in src. Default: **false**

However according to the index.js[1] the default is actually true. 

[1] https://github.com/mrmlnc/syncy/blob/f72ed424ef6646b2a17b7f089d10d477af49d4f4/index.js#L39

**Comment by sbx320** [comment]
On a related note: the base_path parameter seems to be called base now.

**Comment by mrmlnc** [comment]
Hello, @sbx320,

Good catch. I will correct this issue in version 2.1.0.

Thanks you :+1:
